### ISSUE TITLE
Bidirectional functional dependency for Cons

### ISSUE THREAD

**Issue by goldfirere** [phadej/overloaded#11]
If I say

```hs
{-# LANGUAGE DataKinds #-}

{-# OPTIONS_GHC -fplugin=Overloaded -fplugin-opt=Overloaded:Lists -fplugin-opt=Overloaded:TypeNats #-}

module Bug where

import Data.Vec.Lazy (Vec)
import Data.Nat
import Overloaded

foo :: Vec 3 Char
foo = ['a','b','c']

bar = 'd' `cons` foo
```

I get

```
Bug.hs:14:7: error:
    • Ambiguous type variable ‘zs0’ arising from a use of ‘cons’
      prevents the constraint ‘(Cons
                                  Char (Vec ('S ('S ('S 'Z))) Char) zs0)’ from being solved.
      Relevant bindings include bar :: zs0 (bound at Bug.hs:14:1)
      Probable fix: use a type annotation to specify what ‘zs0’ should be.
      These potential instance exist:
        instance Cons a (Vec n a) (Vec ('S n) a)
          -- Defined in ‘Overloaded.Lists’
    • In the expression: 'd' `cons` foo
      In an equation for ‘bar’: bar = 'd' `cons` foo
   |
14 | bar = 'd' `cons` foo
   |       ^^^^^^^^^^^^^^
Failed, no modules loaded.
```

This is because the fundep on `Cons` goes only from results to arguments. Can we get one that goes from arguments to results? Is there an instance you have in mind for `Cons` that won't respect that fundep?

**Comment by phadej** [comment]
That's a design trade-off: I want simple way to support `NonEmpty` construction; the cost is lose of bidirectionality. That would be painful in GHCi, but in GHCI source plugins don't even work.

---

If we add that, then...

```
src/Overloaded/Lists.hs:68:10: error:
    Functional dependencies conflict between instance declarations:
      instance Cons a [a] [a] -- Defined at src/Overloaded/Lists.hs:68:10
      instance Cons a [a] (NonEmpty a)
        -- Defined at src/Overloaded/Lists.hs:71:10
   |
68 | instance Cons a [a] [a] where
   |          ^^^^^^^^^^^^^^
```

---

```diff
-instance Cons a (Vec.Vec n a) (Vec.Vec ('N.S n) a) where
+instance (b ~ c, a ~ b, m ~ 'N.S n) => Cons b (Vec.Vec n c) (Vec.Vec m a) where
     cons = (Vec.:::)
```

allows 

```haskell
asVec :: Vec n a -> Vec n a
asVec = id

bar = asVec ('d' `cons` foo)
```

to compile, i.e. you have to say you want `Vec` but GHC is able to calculate indices.

**Comment by phadej** [comment]
Also even Agda isn't as smart!

![Screenshot from 2019-12-04 12-55-53](https://user-images.githubusercontent.com/51087/70136851-79f10c00-1695-11ea-82cc-b3523d715443.png)

```agda
module Cons where

data Unit : Set where
  unit : Unit

data List (A : Set) : Set where
  nil  : List A
  cons : A -> List A -> List A

data NonEmpty (A : Set) : Set where
  cons : A -> List A -> NonEmpty A

xs : List Unit
xs = cons unit (cons unit nil)

-- the constructor is amgibuous, will be in yellow.
ys = cons xs
```

**Comment by goldfirere** [comment]
OK. That's convincing. Thanks for explaining!

**Comment by phadej** [comment]
In https://github.com/phadej/overloaded/pull/14 I'll introduce `.Bidi` modules for ones who really would like it. I'm not sure about it though.

---

I argue, that bidirectionality is not needed when we are desugaring *lists*, not overloading `cons`.

The GHC is happily inferring

```haskell
*Overloaded> :t True `cons` 'a' `cons` nil
True `cons` 'a' `cons` nil
   :: (Cons Bool ys1 zs, Cons Char ys2 ys1, Nil ys2) => zs
```

which the `[True, 'a']` would desugar to, if GHCi supported source plugins.

Compare that to

```haskell
Overloaded> :t "foo"
"foo" :: Data.String.IsString p => p
```

---

```haskell
*Overloaded> let x = "foo"
*Overloaded> :t x
x :: Data.String.IsString p => p
```

```haskell
*Overloaded> let xs = 'x' `cons` True `cons` nil
*Overloaded> :t xs
xs :: (Cons Char ys1 zs, Cons Bool ys2 ys1, Nil ys2) => zs
```

---

Compare that to compiling the file

```haskell
{-# LANGUAGE NoMonomorphismRestriction #-}
{-# LANGUAGE FlexibleContexts #-}
module Test where

import Overloaded
import Data.String

import Data.Vec.Lazy (Vec)
import qualified Data.Type.Nat as N

x = fromString "foo"

xs = 'x' `cons` True `cons` nil

-- original issue
foo :: Vec N.Nat3 Char
foo = 'a' `cons` 'b' `cons` 'c' `cons` nil

bar = 'd' `cons` foo
```

If we try to compile that, it compiles fine. Due `NoMonomorphismRestriction`. The `bar` is polymorphic, which is bad or not, depends which opinion you have about the`MonomorphismRestriction`.

**Comment by goldfirere** [comment]
I somehow hadn't thought about the fact that the monomorphism restriction was in play. (It's clear in retrospect.) I'm now much less bothered by the inference "failure" here. No need to complicate the library with `.Bidi` purely for my benefit.

**Comment by phadej** [comment]
There's story to be figured out about *type defaulting* though:

```haskell
+Prelude> :set -XOverloadedStrings 
Prelude> "foo"
"foo"
```

works. An example of confusing operations (without bidi) is e.g.

```haskell
Prelude Overloaded> cons () []

<interactive>:7:1: error:
    • No instance for (Cons () [a0] ()) arising from a use of ‘it’
    • In the first argument of ‘print’, namely ‘it’
      In a stmt of an interactive GHCi command: print it
```

the `zs` is defaulted to `()` :)

if `overloaded` worked at GHCi, then enabling it might makes things not work at all.

**Comment by goldfirere** [comment]
Type defaulting can be negotiated. The rules are explained here: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ghci.html#extended-rules-around-default-declarations

They state that multiparameter type classes are simply not involved. However, from previous conversations about defaulting, I've learned that these rules are basically arbitrary. Since plugins don't work in GHCi at the moment, it's not worth pushing the point today, but when they are, it would be reasonable to ask for e.g. multiparameter type class constraints to be checked before choosing a type from the defaulting list. I'm sure there would be some technical debate about it all, but I do think that we could come up with a new story around defaulting that would fix this problem.
